apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
spec:
  selector:
    app: {{ include "web.name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
