apiVersion: v1
kind: Namespace
metadata:
  name: security-lab
  labels:
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "v1.30"
    pod-security.kubernetes.io/warn: "baseline"
    pod-security.kubernetes.io/audit: "baseline"
