apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"assignment3-django-deploy"},"name":"assignment3-django-deploy","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"pod":"assignment3-django-deploy"}},"template":{"metadata":{"labels":{"pod":"assignment3-django-deploy"}},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"thisisatestthing."},{"name":"MYSQL_DB","value":"GiftcardSiteDB"},{"name":"MYSQL_HOST","value":"mysql-service"},{"name":"ALLOWED_HOSTS","value":"*,"}],"image":"nyuappsec/assign3:v0","name":"assignment3-django-deploy","ports":[{"containerPort":8000}],"volumeMounts":[{"mountPath":"/var/lib/busybox","name":"mysql-volume-mount"},{"mountPath":"/vol/static","name":"static-data-volume-mount"}]}],"volumes":[{"name":"mysql-volume-mount","persistentVolumeClaim":{"claimName":"mysql-pvc"}},{"name":"static-data-volume-mount","persistentVolumeClaim":{"claimName":"static-data-pvc"}}]}}}}
  creationTimestamp: "2025-11-07T18:35:44Z"
  generation: 1
  labels:
    app: assignment3-django-deploy
  name: assignment3-django-deploy
  namespace: default
  resourceVersion: "592"
  uid: baedc714-48da-4d65-86d3-3fb520b4b9aa
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      pod: assignment3-django-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        pod: assignment3-django-deploy
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: thisisatestthing.
        - name: MYSQL_DB
          value: GiftcardSiteDB
        - name: MYSQL_HOST
          value: mysql-service
        - name: ALLOWED_HOSTS
          value: '*,'
        image: nyuappsec/assign3:v0
        imagePullPolicy: IfNotPresent
        name: assignment3-django-deploy
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/busybox
          name: mysql-volume-mount
        - mountPath: /vol/static
          name: static-data-volume-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-volume-mount
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: static-data-volume-mount
        persistentVolumeClaim:
          claimName: static-data-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-07T18:36:17Z"
    lastUpdateTime: "2025-11-07T18:36:17Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-07T18:35:44Z"
    lastUpdateTime: "2025-11-07T18:36:17Z"
    message: ReplicaSet "assignment3-django-deploy-679dbffdd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
