apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"mysql-container","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mysql-container"}},"template":{"metadata":{"labels":{"app":"mysql-container","tier":"backend"}},"spec":{"containers":[{"env":[{"name":"MYSQL_ROOT_PASSWORD","value":"thisisatestthing."},{"name":"MYSQL_DATABASE","value":"GiftcardSiteDB"}],"image":"nyuappsec/assign3-db:v0","name":"mysql-container","ports":[{"containerPort":3306}],"volumeMounts":[{"mountPath":"/var/lib/mysql","name":"mysql-volume-mount"}]}],"volumes":[{"name":"mysql-volume-mount","persistentVolumeClaim":{"claimName":"mysql-pvc"}}]}}}}
  creationTimestamp: "2025-11-07T18:35:38Z"
  generation: 1
  name: mysql-container
  namespace: default
  resourceVersion: "564"
  uid: f7c31f08-b8ee-4e3c-8d98-1716a658c1f9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-container
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql-container
        tier: backend
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: thisisatestthing.
        - name: MYSQL_DATABASE
          value: GiftcardSiteDB
        image: nyuappsec/assign3-db:v0
        imagePullPolicy: IfNotPresent
        name: mysql-container
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-volume-mount
        persistentVolumeClaim:
          claimName: mysql-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-07T18:36:03Z"
    lastUpdateTime: "2025-11-07T18:36:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-07T18:35:38Z"
    lastUpdateTime: "2025-11-07T18:36:03Z"
    message: ReplicaSet "mysql-container-699dbd779c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
