apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"proxy"},"name":"proxy","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"pod":"proxy"}},"template":{"metadata":{"labels":{"pod":"proxy"}},"spec":{"containers":[{"image":"nyuappsec/assign3-proxy:v0","name":"proxy","ports":[{"containerPort":8080}],"volumeMounts":[{"mountPath":"/vol/static","name":"static-data-volume-mount"}]}],"volumes":[{"name":"static-data-volume-mount","persistentVolumeClaim":{"claimName":"static-data-pvc"}}]}}}}
  creationTimestamp: "2025-11-07T18:35:50Z"
  generation: 2
  labels:
    app: proxy
  name: proxy
  namespace: default
  resourceVersion: "773"
  uid: 2255a409-c26c-4620-ba1f-af7087077115
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      pod: proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-07T13:38:32-05:00"
      labels:
        pod: proxy
    spec:
      containers:
      - image: nyuappsec/assign3-proxy:v0
        imagePullPolicy: IfNotPresent
        name: proxy
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vol/static
          name: static-data-volume-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: static-data-volume-mount
        persistentVolumeClaim:
          claimName: static-data-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-07T18:38:23Z"
    lastUpdateTime: "2025-11-07T18:38:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-07T18:35:50Z"
    lastUpdateTime: "2025-11-07T18:38:33Z"
    message: ReplicaSet "proxy-79cc86cbb5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
