apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-web
  labels: { app: vote-web }
spec:
  replicas: 1
  selector:
    matchLabels: { app: vote-web }
  template:
    metadata:
      labels: { app: vote-web }
    spec:
      containers:
      - name: web
        image: 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  selector: { app: vote-web }
  ports:
  - port: 80
    targetPort: 80
