version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  nosqldata:
    image: mongo

  basketdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: 
    depends_on:
      - sqldata

  basket-api:
    image: 
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: 
    depends_on:
      - sqldata
      - rabbitmq

  ordering-api:
    image: 
    depends_on:
      - sqldata
      - rabbitmq

  ordering-backgroundtasks:
    image: 
    depends_on:
      - sqldata
      - rabbitmq

  payment-api:
    image: 
    depends_on:
      - rabbitmq

  webhooks-api:
    image: 
    depends_on:
      - sqldata

  mobileshoppingapigw:
    image: envoyproxy/envoy:v1.11.1

  mobileshoppingagg:
    image: 
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: 
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: 
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: 

  webspa:
    image: 
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: 
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: 
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1
