#version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  nosqldata:
    image: mongo

  basketdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: sma9000/identity-api:latest
    depends_on:
      - sqldata

  basket-api:
    image: sma9000/basket-api:latest
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq

  catalog-api:
    image: sma9000/catalog-api:latest
    depends_on:
      - sqldata
      - rabbitmq

  ordering-api:
    image: sma9000/ordering-api:latest
    depends_on:
      - sqldata
      - rabbitmq

  ordering-backgroundtasks:
    image: sma9000/ordering-backgroundtasks:latest
    depends_on:
      - sqldata
      - rabbitmq

  payment-api:
    image: sma9000/payment-api:latest
    depends_on:
      - rabbitmq

  webhooks-api:
    image: sma9000/webhooks-api:latest
    depends_on:
      - sqldata

  mobileshoppingapigw:
    image: envoyproxy/envoy:v1.11.1

  mobileshoppingagg:
    image: sma9000/gateway-mobil-api:latest
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webshoppingagg:
    image: sma9000/gateway-web-api:latest
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  ordering-signalrhub:
    image: sma9000/ordering-signalrhub:latest
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api

  webstatus:
    image: sma9000/webstatus:latest

  webspa:
    image: sma9000/webspa:latest
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webmvc:
    image: sma9000/webmvc:latest
    depends_on:
      - webshoppingagg
      - webshoppingapigw

  webhooks-client:
    image: sma9000/webhooks-api:latest
    depends_on:
      - webhooks-api

  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1