apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-postgres
  labels: { app: vote-postgres }
spec:
  replicas: 1
  selector:
    matchLabels: { app: vote-postgres }
  template:
    metadata:
      labels: { app: vote-postgres }
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - { name: POSTGRES_USER, value: "postgres" }
        - { name: POSTGRES_PASSWORD, value: "postgres" }
        - { name: POSTGRES_DB, value: "votes" }
        ports:
        - containerPort: 5432
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 10
