apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-postgres
  labels: { app: vote-postgres }
spec:
  replicas: 1
  selector:
    matchLabels: { app: vote-postgres }
  template:
    metadata:
      labels: { app: vote-postgres }
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - { name: POSTGRES_USER, value: "postgres" }
        - { name: POSTGRES_PASSWORD, value: "postgres" }
        - { name: POSTGRES_DB, value: "votes" }
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-data
