name: basket-api

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - Code/Homework/src/BuildingBlocks/**
    - Code/Homework/src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - main
    paths:
    - Code/Homework/src/BuildingBlocks/**
    - Code/Homework/src/Services/Basket/**
    - .github/workflows/basket-api.yml

env:
  SERVICE: basket-api
  IMAGE: basket.api

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    
